# Generated by Django 4.2.1 on 2023-06-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='last_time_for_send')),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('CREATED', 'Created'), ('RUNNING', 'Running')])),
                ('mail_answer', models.CharField(verbose_name='answer_from_mailserver')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='message_theme')),
                ('body', models.TextField(max_length=500, verbose_name='message_body')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='start_time_for_sending')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')])),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('CREATED', 'Created'), ('RUNNING', 'Running')])),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.attempt')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='client_name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='comment_about_client')),
                ('email', models.EmailField(help_text='client name for mailing', max_length=255, verbose_name='client_mail')),
                ('transmission', models.ManyToManyField(to='mailing.transmission')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
