# Generated by Django 4.2.2 on 2023-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='client_name')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='comment_about_client')),
                ('email', models.EmailField(help_text='client name for mailing', max_length=255, verbose_name='client_mail')),
                ('transmission', models.ManyToManyField(to='mailing.transmission')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
