# Generated by Django 4.2.1 on 2023-06-08 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmission',
            name='date',
        ),
        migrations.AlterField(
            model_name='transmission',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0), verbose_name='start time for sending'),
        ),
    ]
