# Generated by Django 4.2.2 on 2023-06-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_transmission_owner_alter_transmission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
