# Generated by Django 4.2.1 on 2023-06-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_transmission_date_alter_transmission_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last time for send')),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('CREATED', 'Created')], default='CREATED')),
                ('mail_answer', models.CharField(blank=True, default=None, null=True, verbose_name='answer from mailserver')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
            },
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='attempt',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.AddField(
            model_name='statistic',
            name='transmission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.transmission'),
        ),
    ]
