# Generated by Django 4.2.1 on 2023-06-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_statistic_remove_transmission_attempt_delete_attempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='transmission',
        ),
        migrations.AddField(
            model_name='transmission',
            name='statistic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.statistic'),
        ),
    ]
